name = "ATLabData"
uuid = "2001816d-1027-44d7-a455-52de789fd3bf"
version = "1.0.0-DEV"
authors = ["Thomas Vandamme"]

[deps]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
