name = "ATLabData"
uuid = "2001816d-1027-44d7-a455-52de789fd3bf"
version = "1.0.0-DEV"
authors = ["Thomas Vandamme"]

[deps]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ForwardDiff = "1.3.0"
SimpleNonlinearSolve = "2.9.0"
julia = "1.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
